### ISSUE TITLE
No indication a log in is being processed.

### ISSUE THREAD

**Issue by runboxdave** [runbox/runbox7#30]
There is little indication a log in is being processed. 

This is specifically a problem after a failed login and especially if you then get another failed login. You are left wondering if the second attempt was being processed or not as the previous error message stays on screen. Maybe as you type in a new password or 2FA code the previous message should be cleared?

**Comment by petersalomonsen** [comment]
Isn't this already fixed here: https://github.com/runbox/runbox7/pull/16

Or am I missing something?

**Comment by davidbowdley** [comment]
I think it may still be an issue, and specifically when there are two consecutive failed logins. I've been in the situation where the page shows no sign of doing anything or updating the log in error message. I don't see the loading spinner mentioned in the other issue at all.

**Comment by gtandersen** [comment]
@davidbowdley It's a progress bar (not a spinner) underneath the login box. I'm seeing it in Firefox after a failed login as well. Could you capture and upload what you are seeing?

**Comment by davidbowdley** [comment]
@geir I see nothing. No progress bar on a repeated failed login. No action on the screen at all. It gives the impression that pressing the log in button doesn’t do anything. The progress bar only shows on a successful log in.

**Comment by gtandersen** [comment]
@davidbowdley When attempting to reproduce this (Firefox, Chrome) a progress bar is shown at the bottom of the login screen regardless of whether a username/password combination is correct. Can you upload a screen recording of what you are seeing if a progress bar is still not shown?

**Comment by gtandersen** [comment]
@runboxdave The progress bar is now shown at the bottom of the tab/window and in Firefox on macOS it is also displayed on repeated failed logins.

Can you confirm?

**Comment by gtandersen** [comment]
Closing this issue since it appears to be resolved satisfactorily.
